import type { QrMagicProject } from "../types";

export const initialProject: QrMagicProject = {
  version: 1,
  document: {
    name: "Festival Parking Decal",
    unit: "in",
    width: 4,
    height: 3,
    dpi: 300,
    backgroundColor: "#f8fafc",
  },
  layers: [
    {
      id: "layer_artwork_background",
      type: "shape",
      shape: "rectangle",
      name: "Artwork Background",
      visible: true,
      locked: false,
      x: 36,
      y: 36,
      width: 1128,
      height: 828,
      rotation: 0,
      opacity: 0.94,
      fill: "#f59e0b",
      stroke: "transparent",
      strokeWidth: 0,
      dash: [],
      cornerRadius: 18,
    },
    {
      id: "layer_cutline",
      type: "shape",
      shape: "rectangle",
      name: "Cutline / Safe Area",
      visible: true,
      locked: false,
      x: 82,
      y: 82,
      width: 1036,
      height: 736,
      rotation: 0,
      opacity: 0.65,
      fill: "transparent",
      stroke: "#111827",
      strokeWidth: 8,
      dash: [18, 16],
      cornerRadius: 24,
    },
    {
      id: "layer_title",
      type: "text",
      name: "Title",
      visible: true,
      locked: false,
      x: 96,
      y: 108,
      width: 760,
      height: 70,
      rotation: 0,
      opacity: 1,
      textTemplate: "FESTIVAL PARKING",
      fontFamily: "Inter, Arial, sans-serif",
      fontSize: 54,
      fontWeight: 800,
      fill: "#111827",
      align: "left",
    },
    {
      id: "layer_subtitle",
      type: "text",
      name: "Subtitle",
      visible: true,
      locked: false,
      x: 100,
      y: 184,
      width: 560,
      height: 38,
      rotation: 0,
      opacity: 1,
      textTemplate: "LOT A - WEEKEND ACCESS",
      fontFamily: "Inter, Arial, sans-serif",
      fontSize: 28,
      fontWeight: 700,
      fill: "#374151",
      align: "left",
    },
    {
      id: "layer_qr",
      type: "qr",
      name: "QR Code",
      visible: true,
      locked: false,
      x: 780,
      y: 300,
      width: 260,
      height: 260,
      rotation: 0,
      opacity: 1,
      payloadTemplate: "{{serial}}",
      foreground: "#111827",
      background: "#ffffff",
    },
    {
      id: "layer_serial",
      type: "text",
      name: "Serial",
      visible: true,
      locked: false,
      x: 710,
      y: 585,
      width: 400,
      height: 58,
      rotation: 0,
      opacity: 1,
      textTemplate: "{{serial}}",
      fontFamily: "Inter, Arial, sans-serif",
      fontSize: 42,
      fontWeight: 800,
      fill: "#111827",
      align: "center",
    },
  ],
  data: {
    mode: "serial",
    serial: {
      prefix: "PARK-",
      suffix: "",
      start: 1,
      quantity: 10,
      step: 1,
      padding: 4,
    },
  },
  export: {
    filenameTemplate: "{{serial}}",
    formats: ["png"],
    renderMode: "flattened",
  },
};

export function documentPixelSize(project: QrMagicProject) {
  if (project.document.unit === "px") {
    return {
      width: project.document.width,
      height: project.document.height,
    };
  }

  if (project.document.unit === "mm") {
    return {
      width: Math.round((project.document.width / 25.4) * project.document.dpi),
      height: Math.round((project.document.height / 25.4) * project.document.dpi),
    };
  }

  return {
    width: Math.round(project.document.width * project.document.dpi),
    height: Math.round(project.document.height * project.document.dpi),
  };
}
